### ISSUE TITLE
chmod +x rank.py command error

### ISSUE THREAD

**Issue by AbhiRodi** [sundios/Google-rank-tracker#10]
Whenever I run this command its, always giving me error listed below.

chmod : The term 'chmod' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At line:1 char:1
+ chmod +x rank.py
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (chmod:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by sundios** [comment]
chmod is a command in Unix and Unix-like operating systems that change the access permissions of files and directories. So If you are in windows or something else, I guess it's a different command.  I found this --> https://superuser.com/questions/106181/equivalent-of-chmod-to-change-file-permissions-in-windows

Also, I don't think you need to give file permissions tu run the script. Try running it and see what happens.

**Comment by AbhiRodi** [comment]
![Screenshot 2022-11-03 111206](https://user-images.githubusercontent.com/88835985/199654542-84ed9b8e-11d4-48cc-b15a-eb98d4c11113.png)

**Comment by sundios** [comment]
Read the documentation and you will find your answer
