### ISSUE TITLE
multiple csv

### ISSUE THREAD

**Issue by brenovieira** [sundios/Google-rank-tracker#2]
It would be great if this script could handle multiple keywords to create only 1 CSV not multiple CSVs and do random sleeps between each keyword..

The problem is that I have a blog with ~200 pages, and having 200 csv is a big problem for me.

from your experience, 20-30 seconds is enough to Google dont show captcha?

another thing, would be nice if you add mobile user agents as well.

I don't know python, but I will try to set up the script on this weekend, and maybe I can help with these changes as well
Thanks

**Comment by santma** [comment]
Hey! Good suggestions! Its a work in progress, so I'll keep that in mind.
The script should output 3 csvs, not 200. But, maybe you're using it a but
differently. It's a fresh project, so any tips are welcome. Thanks again!

**Comment by sundios** [comment]
Hi Bruno, 

That's a good idea. What I have done in the past (Which is not very optimal) is to create one folder for each keyword I want to run and then save each output on a separate folder, then I run a script that concatenate all the files into one master file.I know it would be hard to escalate but that's an option. You can find what i mean here --> https://github.com/sundios/SEO-Free-Rank-Check/tree/master/dags

In terms of time outs or sleep, make sure its random numbers between 10 and 40 seconds. 

Good idea I will add mobile user agents, I can't remember why I didn't add them, but I tried and I had some issue but can't remember. I will revisit that soon..

Thanks again

**Comment by brenovieira** [comment]
Hey @sundios , that's great.
Thanks for answering. I will check that out :)

**Comment by sundios** [comment]
I added mobile user agent! Please take a look and let me know what you think. 

Will try to add the CSV exporter for keywords in bulk 👍
