### ISSUE TITLE
New feature request in Google rank tracker | Competitors ranking (SEO)

### ISSUE THREAD

**Issue by susheelseth** [sundios/Google-rank-tracker#4]
Thank you so much Sundios for making this awesome script.  

Here I am requesting for a new feature that will saves a lot of time and help in removing repetitive tasks, i.e. fetching competitors ranking in a single google search command.

Now, we have everything working: 
1. Ability to search multiple keywords via xls file.
2. Fetching top 100 results
3. Searching the input URL and counting the ranking
3. Saving the result in a csv file.

In most of the cases, we also have to search for the competitors rank as well for the same keyword.
Since, we are checking for a single website via command `rank.py https://www.xyz.com/ desktop ` can we tweak a little bit to find the rank of other input URLs.

Method 1 - Run this command - **`rank.py https://www.xyz1.com/ https://www.xyz2.com/ https://www.xyz3.com/ desktop`** so that the scripts checks for all the websites (xyz2, xyz3) and save their corresponding ranking in the csv file.

Method 2 - Run this command -  **`rank.py desktop`** and put the URLs in the same keywords xls file, so that the scripts pick the keywords and URLs from the .xls file and save their corresponding ranking in the csv file.

Output could be like this:
```
Keyword | URL1Rank | URL1 | URL2Rank | URL2 | URL3Rank | URL3 | Device | Date
loan software | 42 | https://www.xyz1.com/xxxx | 30 | https://www.xyz2.com/xxxx | 11 | https://www.xyz3.com/xxxx desktop | ########

```
If something could be done then it will be very helpful and it saves a lot of time.

**Comment by dimitryzub** [comment]
@susheelseth As an alternative, there's a [Google Search Engine Results API](https://serpapi.com/search-api) from SerpApi which is a paid API with a free plan. 

#### Example code that might satisfy Method 2 or give you an idea

You can test it in the [online IDE](https://replit.com/@DimitryZub1/Google-Search-Rank-Tracker?v=1) (add your SerpApi API key under `Secrets` -> `New Secret`), or grab it from [GitHub Gist](https://gist.github.com/dimitryzub/6264c5f2e55e3704eae3fd3f55cda85c) but you also need to pass your API key.

```python
from serpapi import GoogleSearch
from datetime import date
import pandas as pd
import json


def google_website_ranker():
    keywords = pd.read_csv("sample-keywords.csv")["Keywords"].to_list()
    target_websites = pd.read_csv("sample-keywords.csv")["Target-Website"].to_list()

    website_ranking = []

    for index, (keyword, target_website) in enumerate(zip(keywords, target_websites), start=1):
        # print(keyword, target_website)
        params = {
            "api_key": "your-serpapi-api-key",
            "engine": "google",              # search engine 
            "q": keyword,                    # search query
            "google_domain": "google.com",   # google domain
            "gl": "us",                      # country of the search
            "hl": "en",                      # language of the search
            "num": "100",                    # number of results
            "device": "desktop"              # desktop, tablet, mobile
            # other parameters
        }

        search = GoogleSearch(params)    # where data extraction happens
        results = search.get_dict()      # JSON -> Python dict

        if not "error" in results:
            for result in results["organic_results"]:
                if target_website in result["link"] and result["displayed_link"]:
                    website_ranking.append({
                        "keyword": keyword,
                        "rank": f'{result["position"]} (URL{index}Rank)',
                        "target_website": f'{target_website} (URL{index})',
                        "device": params["device"],
                        "date": str(date.today())
                    })
        else:
            print(results["error"])

    print(json.dumps(website_ranking, indent=2, ensure_ascii=False))

    pd.DataFrame(data=website_ranking).to_csv(f"rank-tracking-{str(date.today())}.csv", index=False, encoding="utf-8")


if __name__ == "__main__":
    google_website_ranker()
```

- Multiple keywords and corresponding target website inside CSV file to search from:

![image](https://user-images.githubusercontent.com/78694043/173551586-b7d8ec9f-cf3c-4968-acc1-ea129b079f65.png)

- Fetches 100 results. `"num": "100"`
- Searches the input URL and searches for matches. `if target_website in result["link"] and result["displayed_link"]`
- Outputs `keyword`, `target_website_rank`, `target_website`, `device`, `date`: 

![image](https://user-images.githubusercontent.com/78694043/174039469-5a22c489-2969-4eb7-9cc6-7520e1be2624.png)

**Comment by sundios** [comment]
@dimitryzub SERPapi looks pretty cool!

**Comment by dimitryzub** [comment]
@sundios Thank you so much 🙂 ✨

If you ever want to test it out, [reach out to us](https://serpapi.com/#contact) by mentioning this thread, and we'll give you more than 100 searches (100 searches is a limit of a free plan).

**Comment by sundios** [comment]
I have added competitors to the script.
