### ISSUE TITLE
Not showing any ranking 

### ISSUE THREAD

**Issue by slim-python** [sundios/Google-rank-tracker#6]
I don't know much, but i think it's not working like it should
![image](https://user-images.githubusercontent.com/55599278/122616225-9a31c180-d0a7-11eb-8378-35f0dc89924b.png)

**Comment by sundios** [comment]
Hi,

You need to update the keywords.xls file with your keywords.  ghacks.net will not rank for `giant Toblerone` or `useless things to buy` . Those keywords are meant as an example for the site https://www.uselessthingstobuy.com.

**Comment by saamerm** [comment]
@slim-python can you check if your issue is related to #7 ?
