### ISSUE TITLE
Blocked by Google

### ISSUE THREAD

**Issue by saamerm** [sundios/Google-rank-tracker#7]
I went to the function `def desktop(keyword,sitename,device,useragent):` and under the line `browser.open(...`, I added a line:
`print(browser)` to print the output. 

If you are blocked, it will say `<RoboBrowser url=https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Dthe%2Bfirst_prototype&q=EgRsqoWdGLO1jYcGIhAgHPLrEoXTpalTKCP5PuFaMgFy>` in the output window. 

I went to the link in my browser, I said I am not a robot, and it redirected me to the Google Search. But when I came back to the Robobrowser, it still gave me the same error. I'm at a roadbloack now and can't do any searches with Robobrowser.

Any recommendations?

**Comment by sundios** [comment]
I would recommend always use proxies if you are trying to make lots of searches. 

I haven't added the possibility to use proxies but I will when I get some time. Maybe you can add this as an enhancement or make a pull request

**Comment by saamerm** [comment]
@sundios btw check this out https://github.com/saamerm/Bing-search-rank-tracker

I did have the same issue with bing as well unfortunately 😆

**Comment by sundios** [comment]
@saamerm nice! Maybe I can include a flag to select the search engine :) 

This is great. Thank you!
